name: employme
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  http: ^1.3.0
  hydrated_bloc: ^10.0.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  shared_preferences: ^2.5.2
  skeletonizer: ^1.4.3
  smooth_page_indicator: ^1.2.0+3
  timeline_tile: ^2.0.0
  url_launcher: ^6.3.1
  url_strategy: ^0.3.0
  flutter_launcher_icons: ^0.14.3


dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/company/
    - assets/icons/
    - assets/icons/navbar/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png" 
  remove_alpha_ios: true